server:
  forward-headers-strategy: ${SERVER_FORWARD_HEADERS_STRATEGY:none}

spring:
  application:
    name: "IoT-DeviceTracker-Backend"
    version: 0.0.1

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/iotdtdev}
    username: ${SPRING_DATASOURCE_USERNAME:iotdtdev}
    password: ${SPRING_DATASOURCE_PASSWORD:iotdtdev}
    driver-class-name: org.postgresql.Driver

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  flyway:
    enabled: true
    locations: "classpath:db/migrations"
    baseline-on-migrate: false

  mail:
    host: ${SPRING_MAIL_HOST:}
    port: ${SPRING_MAIL_PORT:}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}

  autoconfigure:
    exclude:
      # Disable unused influx packages
      - com.influxdb.spring.health.InfluxDB2HealthIndicatorAutoConfiguration
      - com.influxdb.spring.influx.InfluxDB2AutoConfigurationReactive

influx:
  url: ${INFLUX_URL:http://127.0.0.1:8086}
  username: ${INFLUX_USERNAME:iotdtdev}
  password: ${INFLUX_PASSWORD:iotdtdev}
  token: ${INFLUX_TOKEN:}
  org: ${INFLUX_ORG:thkoeln}
  bucket: ${INFLUX_BUCKET:iotdt}

logging.level.root: ${LOGGING_LEVEL_ROOT:info}
springdoc:
  swagger-ui:
    supported-submit-methods:
