@startuml
!$sys_admin = "Systemadmin"
!$client = Nutzer
!$admin = "Admin"
!$observer = "Betrachter"
!$iot = "IoT-Gerät"

!$LF01_1 = "/LF01.1/ Anmeldung"
!$LF01_2 = "/LF01.2/ Abmeldung"
!$LF02 = "/LF02/ Registrierung"
!$LF03 = "/LF03/ Konto löschen"
!$LF04 = "/LF04/ User anzeigen"
!$LF05 = "/LF05/ User bearbeiten"
!$LF06 = "/LF06/ User löschen"
!$LF07 = "/LF07/ E-Mail Adresse bestätigen"
!$LF08 = "/LF08/ E-Mail Adresse ändern"
!$LF09_1 = "/LF09.1/ Passwort ändern"
!$LF09_2 = "/LF09.2/ Passwort zurücksetzten"
!$LF10 = "/LF10/ Devices hinzufügen"
!$LF11 = "/LF11/ Devices anzeigen"
!$LF12 = "/LF12/ Devices bearbeiten"
!$LF13 = "/LF13/ Devices entfernen"
!$LF20 = "/LF20/ Device Group hinzufügen"
!$LF21 = "/LF21/ Device Group anzeigen"
!$LF22 = "/LF22/ Device Group bearbeiten"
!$LF23 = "/LF23/ Device Group entfernen"
!$LF30 = "/LF30/ Nutzer zu Device Group hinzufügen"
!$LF31 = "/LF31/ Nutzer der Device Group anzeigen"
!$LF32 = "/LF32/ Nutzer der Device Group bearbeiten"
!$LF33 = "/LF33/ Nutzer in Device Group entfernen"
!$LF34 = "/LF34/ Einladung zu Device Group erstellen"
!$LF35 = "/LF35/ Einladung zu Device Group annehmen"
!$LF40 = "/LF40/ Metriken senden"
!$LF41 = "/LF41/ Aktuelle Metriken einsehen"
!$LF42 = "/LF42/ Alte Metriken einsehen"
!$LF50 = "/LF50/ TOTP konfigurieren"
!$LF51 = "/LF51/ TOTP Status sehen"
!$LF52 = "/LF52/ TOTP deaktivieren"
@enduml